<a href="https://colab.research.google.com/github/mtello5/IS170_Machine_Learning/blob/K-Nearest-Neighbors/HW7_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HW 7 K-Nearest Neighbors | Matthew Tello

In [ ]:
#import scikit-learn dataset library
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [ ]:
#load dataset
from google.colab import files
uploaded = files.upload()

Saving Loan_Default.csv to Loan_Default.csv


In [ ]:
# Read data from CSV file
df = pd.read_csv('Loan_Default.csv')
df.head()

ID  year loan_limit             Gender approv_in_adv loan_type  \
0  24890  2019         cf  Sex Not Available         nopre     type1   
1  24891  2019         cf               Male         nopre     type2   
2  24892  2019         cf               Male           pre     type1   
3  24893  2019         cf               Male         nopre     type1   
4  24894  2019         cf              Joint           pre     type1   

  loan_purpose Credit_Worthiness open_credit business_or_commercial  ...  \
0           p1                l1        nopc                  nob/c  ...   
1           p1                l1        nopc                    b/c  ...   
2           p1                l1        nopc                  nob/c  ...   
3           p4                l1        nopc                  nob/c  ...   
4           p1                l1        nopc                  nob/c  ...   

   credit_type  Credit_Score  co-applicant_credit_type    age  \
0          EXP           758                       CIB  25-34   
1         EQUI           552                       EXP  55-64   
2          EXP           834                       CIB  35-44   
3          EXP           587                       CIB  45-54   
4         CRIF           602                       EXP  25-34   

   submission_of_application        LTV Region Security_Type  Status dtir1  
0                    to_inst  98.728814  south        direct       1  45.0  
1                    to_inst        NaN  North        direct       1   NaN  
2                    to_inst  80.019685  south        direct       0  46.0  
3                   not_inst  69.376900  North        direct       0  42.0  
4                   not_inst  91.886544  North        direct       0  39.0  

[5 rows x 34 columns]

In [ ]:
#Getting the features of this dataset
df.columns

Index(['ID', 'year', 'loan_limit', 'Gender', 'approv_in_adv', 'loan_type',
       'loan_purpose', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'income', 'credit_type', 'Credit_Score', 'co-applicant_credit_type',
       'age', 'submission_of_application', 'LTV', 'Region', 'Security_Type',
       'Status', 'dtir1'],
      dtype='object')

In [ ]:
#Show new table with unnecessary columns dropped
df.head()

ID  year loan_limit             Gender approv_in_adv loan_type  \
0  24890  2019         cf  Sex Not Available         nopre     type1   
1  24891  2019         cf               Male         nopre     type2   
2  24892  2019         cf               Male           pre     type1   
3  24893  2019         cf               Male         nopre     type1   
4  24894  2019         cf              Joint           pre     type1   

  loan_purpose Credit_Worthiness open_credit business_or_commercial  ...  \
0           p1                l1        nopc                  nob/c  ...   
1           p1                l1        nopc                    b/c  ...   
2           p1                l1        nopc                  nob/c  ...   
3           p4                l1        nopc                  nob/c  ...   
4           p1                l1        nopc                  nob/c  ...   

   credit_type  Credit_Score  co-applicant_credit_type    age  \
0          EXP           758                       CIB  25-34   
1         EQUI           552                       EXP  55-64   
2          EXP           834                       CIB  35-44   
3          EXP           587                       CIB  45-54   
4         CRIF           602                       EXP  25-34   

   submission_of_application        LTV Region Security_Type  Status dtir1  
0                    to_inst  98.728814  south        direct       1  45.0  
1                    to_inst        NaN  North        direct       1   NaN  
2                    to_inst  80.019685  south        direct       0  46.0  
3                   not_inst  69.376900  North        direct       0  42.0  
4                   not_inst  91.886544  North        direct       0  39.0  

[5 rows x 34 columns]

In [ ]:
#Feature EngineerinG
df.shape

(148670, 34)

In [ ]:
#Deleting out NaN values
df = df.dropna()

In [ ]:
print(df.isna().sum())

ID                           0
year                         0
loan_limit                   0
Gender                       0
approv_in_adv                0
loan_type                    0
loan_purpose                 0
Credit_Worthiness            0
open_credit                  0
business_or_commercial       0
loan_amount                  0
rate_of_interest             0
Interest_rate_spread         0
Upfront_charges              0
term                         0
Neg_ammortization            0
interest_only                0
lump_sum_payment             0
property_value               0
construction_type            0
occupancy_type               0
Secured_by                   0
total_units                  0
income                       0
credit_type                  0
Credit_Score                 0
co-applicant_credit_type     0
age                          0
submission_of_application    0
LTV                          0
Region                       0
Security_Type                0
Status  

We got rid of all rows will null values so we can work with just the data that is complete.

In [ ]:
df.shape

(98187, 34)

In [ ]:
X = df[['loan_amount', 'rate_of_interest','term','property_value','income','Credit_Score','dtir1']] .values
X[0:5]

array([[4.065e+05, 4.560e+00, 3.600e+02, 5.080e+05, 9.480e+03, 8.340e+02,
        4.600e+01],
       [6.965e+05, 4.000e+00, 3.600e+02, 7.580e+05, 1.044e+04, 6.020e+02,
        3.900e+01],
       [7.065e+05, 3.990e+00, 3.600e+02, 1.008e+06, 1.008e+04, 8.640e+02,
        4.000e+01],
       [3.465e+05, 4.500e+00, 3.600e+02, 4.380e+05, 5.040e+03, 8.600e+02,
        4.400e+01],
       [3.765e+05, 4.875e+00, 3.600e+02, 4.780e+05, 5.580e+03, 5.800e+02,
        4.400e+01]])

In [ ]:
# Convert single column to int dtype.
lt_map = {'type1': 1, 'type2': 2, 'type3': 3}
df['loan_type'] = df['loan_type'].map(lt_map)

In [ ]:
y = df['loan_type'].values
y[0:5]

array([1, 1, 1, 1, 1])

In [ ]:
# Standardizing the data
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[ 0.4161456 ,  0.90108864,  0.43701358, -0.0024823 ,  0.36823608,
         1.16273968,  0.86017687],
       [ 2.07290046, -0.14672761,  0.43701358,  0.72628761,  0.5230328 ,
        -0.84295847,  0.16205829],
       [ 2.13002994, -0.16543861,  0.43701358,  1.45505751,  0.46498403,
         1.4220972 ,  0.26178952],
       [ 0.07336873,  0.78882262,  0.43701358, -0.20653788, -0.34769876,
         1.3875162 ,  0.66071442],
       [ 0.24475717,  1.49048529,  0.43701358, -0.08993469, -0.2606256 ,
        -1.03315399,  0.66071442]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (78549, 7) (78549,)
Test set: (19638, 7) (19638,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:


k = 3
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=3)

In [ ]:
yhat = neigh.predict(X_test)
yhat[0:5]

array([1, 1, 1, 1, 1])

In [ ]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.8999605341888502
Test set Accuracy:  0.8464711274060495


In [ ]:
k = 3
neigh3 = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
yhat3 = neigh3.predict(X_test)
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh3.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat3))

Train set Accuracy:  0.8992985270340806
Test set Accuracy:  0.8491190548935736


In [ ]:
k = 5
neigh5 = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
yhat5 = neigh5.predict(X_test)
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh5.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat5))

Train set Accuracy:  0.8844415587722313
Test set Accuracy:  0.8580303493227416


In [ ]:
k = 7
neigh7 = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
yhat7 = neigh7.predict(X_test)
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh7.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat7))

Train set Accuracy:  0.8795910832728615
Test set Accuracy:  0.8620531622364803


Dear Boss,
KNN is an example of a machine learning algorithm known as K-Nearest Neighbors.
On the basis of information about the borrower, it is used to anticipate whether a loan will default or not. The algorithm considers a variety of parameters, including the borrower's credit score, income, loan amount, etc.
The system then compares these parameters to those of comparable borrowers in the past and generates a prediction based on their outcomes.
KNN is a good technique for predicting loan defaults since it is able to produce accurate forecasts based on the experiences of comparable borrowers. 