<a href="https://colab.research.google.com/github/mtello5/IS170_Machine_Learning/blob/Naive-Bayes/Naive_Bayes_LAB8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lab 8 - Matthew Tello, Jonathan Saligan**




# **Naive Bayes **

The kids can play outside if the outlook and temp permit. Any adversarial outlook or high or low temp, the kids can't.

In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv("/content/player.csv")
df

day   outlook temperature humidity    wind playgolf
0     1     sunny         hot     high    weak       no
1     2     sunny         hot     high  strong       no
2     3  overcast         hot     high    weak      yes
3     4      rain        mild     high    weak      yes
4     5      rain        cool   normal    weak      yes
5     6      rain        cool     high  strong       no
6     7  overcast        cool     high  strong      yes
7     8     sunny        mild     high    weak       no
8     9     sunny        cool   normal    weak      yes
9    10      rain        mild     high    weak      yes
10   11     sunny        mild     high  strong      yes
11   12  overcast        mild     high  strong      yes
12   13  overcast         hot   normal    weak      yes
13   14      rain        mild     high  strong       no

In [ ]:
#In order to process we must turn those categorical values into numberic values
#Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

#Using .fit_transform function to fit label
#encoder and return encoded label
outlook_label=le.fit_transform(df['outlook'])

#printing outlook_label
outlook_label

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [ ]:
#repeat it for temp label
temp_label=le.fit_transform(df['temperature'])

#printing temp_label
temp_label

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [ ]:
#repeat it for play label
play_label=le.fit_transform(df['playgolf'])

#printing play_label
play_label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
#we'll use zip method in this function called merge to combine the two labels: outlook and temp
def merge (list1, list2):
  merged_list=tuple(zip(list1, list2))
  return merged_list

features=merge(outlook_label, temp_label)
features


((2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2))

In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,play_label)

#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

Predicted Value: [1]


Based if outlook is overcast (0) and temperature is mild (2) it is predicted to play golf

# **Naive Bayes using Multiple Labels**

In [ ]:
df2=pd.read_csv("/content/player.csv")
df2.head()


day   outlook temperature humidity    wind playgolf
0    1     sunny         hot     high    weak       no
1    2     sunny         hot     high  strong       no
2    3  overcast         hot     high    weak      yes
3    4      rain        mild     high    weak      yes
4    5      rain        cool   normal    weak      yes

In [ ]:
categ = ['outlook','temperature','humidity','wind','playgolf']

# Encode Categorical Columns
le = preprocessing.LabelEncoder()
df2 = df2[categ] = df2[categ].apply(le.fit_transform)
df2

outlook  temperature  humidity  wind  playgolf
0         2            1         0     1         0
1         2            1         0     0         0
2         0            1         0     1         1
3         1            2         0     1         1
4         1            0         1     1         1
5         1            0         0     0         0
6         0            0         0     0         1
7         2            2         0     1         0
8         2            0         1     1         1
9         1            2         0     1         1
10        2            2         0     0         1
11        0            2         0     0         1
12        0            1         1     1         1
13        1            2         0     0         0

In [ ]:
x_data = df2[['outlook', 'temperature', 'humidity', 'wind']]
y_data = df2['playgolf']

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3,random_state=109) # 70% training and 30% test

In [ ]:
#This is model generation

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

#Train the model using the training sets
model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

#This is to evaluate the model
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.4


With this model, we received a 40% accuracy in the factors of outlook, temperature, humidity, and wind in determing if we will be able to play golf.
